# Generated by Django 5.0.3 on 2026-05-27 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PME",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("secteur", models.CharField(max_length=100)),
                ("email_contact", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("a_repondu", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/pme/%Y/"
                    ),
                ),
                (
                    "quota_stockage",
                    models.IntegerField(
                        default=200,
                        help_text="Quota de stockage partagé pour toute la PME (Go)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "PME",
                "verbose_name_plural": "PMEs",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("general", "Général"),
                            ("financier", "Financier"),
                            ("operationnel", "Opérationnel"),
                            ("rh", "Ressources Humaines"),
                        ],
                        max_length=100,
                    ),
                ),
                ("ordre", models.IntegerField(default=0)),
                ("obligatoire", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="DemandeAugmentationQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quota_actuel",
                    models.IntegerField(
                        help_text="Quota en Go au moment de la demande"
                    ),
                ),
                (
                    "quota_demande",
                    models.IntegerField(
                        help_text="Quota souhaité en Go",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("traite", models.BooleanField(default=False)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "quota_accorde",
                    models.IntegerField(
                        blank=True,
                        help_text="Quota accordé par l'admin en Go",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'augmentation de quota",
                "verbose_name_plural": "Demandes d'augmentation de quota",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="DemandeMotDePasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Motif ou précisions de l'utilisateur"
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("traite", models.BooleanField(default=False)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_mdp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de mot de passe",
                "verbose_name_plural": "Demandes de mot de passe",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "dossier_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_dossiers",
                        to="survey.dossier",
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
            },
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("signup", "Inscription"), ("login", "Connexion")],
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP email",
                "verbose_name_plural": "OTPs email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Fichier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("fichier", models.FileField(blank=True, upload_to="fichiers/%Y/%m/")),
                ("nextcloud_path", models.CharField(blank=True, max_length=512)),
                ("nextcloud_etag", models.CharField(blank=True, max_length=128)),
                ("stockage_externe", models.BooleanField(default=False)),
                ("taille", models.BigIntegerField(default=0)),
                ("type_mime", models.CharField(blank=True, max_length=100)),
                ("chiffre", models.BooleanField(default=True)),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("est_favori", models.BooleanField(default=False)),
                ("est_corbeille", models.BooleanField(default=False)),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fichiers",
                        to="survey.dossier",
                    ),
                ),
                (
                    "partage_avec",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fichiers_partages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fichiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier",
                "verbose_name_plural": "Fichiers",
                "ordering": ["-date_upload"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quota_stockage",
                    models.IntegerField(
                        default=50,
                        help_text="Quota en Go",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("employe", "Employé"),
                            ("rh", "RH"),
                            ("compta", "Comptabilité"),
                            ("invite", "Invité"),
                        ],
                        default="employe",
                        max_length=20,
                    ),
                ),
                ("service", models.CharField(blank=True, max_length=100)),
                ("deux_facteurs_actif", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/profils/%Y/"
                    ),
                ),
                (
                    "pme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="utilisateurs",
                        to="survey.pme",
                        verbose_name="PME",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="Reponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte_reponse", models.TextField()),
                ("date_reponse", models.DateTimeField(auto_now_add=True)),
                (
                    "pme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="survey.pme",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="survey.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse",
                "verbose_name_plural": "Réponses",
                "unique_together": {("pme", "question")},
            },
        ),
    ]
