# Generated by Django 5.0.3 on 2026-07-24 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copier_partages_existants(apps, schema_editor):
    PartageFichier = apps.get_model('survey', 'PartageFichier')
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names()
        if 'survey_fichier_partage_avec' not in tables:
            return
        cursor.execute(
            'SELECT fichier_id, user_id FROM survey_fichier_partage_avec'
        )
        for fichier_id, user_id in cursor.fetchall():
            PartageFichier.objects.using(db_alias).get_or_create(
                fichier_id=fichier_id,
                destinataire_id=user_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_pme_nom_normalise"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartageFichier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mot_de_passe", models.CharField(blank=True, max_length=128)),
                ("date_partage", models.DateTimeField(auto_now_add=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages_recus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fichier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages",
                        to="survey.fichier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partage de fichier",
                "verbose_name_plural": "Partages de fichiers",
                "unique_together": {("fichier", "destinataire")},
            },
        ),
        migrations.RunPython(copier_partages_existants, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="fichier",
            name="partage_avec",
        ),
        migrations.AddField(
            model_name="fichier",
            name="partage_avec",
            field=models.ManyToManyField(
                blank=True,
                related_name="fichiers_partages",
                through="survey.PartageFichier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
