# Generated by Django 5.0.3 on 2026-07-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_partagefichier"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mode_stockage",
            field=models.CharField(
                choices=[("local", "Local"), ("distance", "À distance")],
                default="distance",
                max_length=10,
                verbose_name="Mode de stockage",
            ),
        ),
    ]
